// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package gov.atlanta.cityvendors.domain;

import gov.atlanta.cityvendors.domain.Vendor;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Vendor_Roo_Configurable {
    
    declare @type: Vendor: @Configurable;
    
}
